name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install MeshFlash from local
        run: |
          pip3 install .
      - name: See if the executable is in our path
        run: |
          which MeshFlash
      - name: Validate we can run it
        run: |
          MeshFlash -h
      - name: Install pyinstaller
        run: |
          pip install pyinstaller
      - name: Build exe
        run: |
          pyinstaller -F -n MeshFlash MeshFlash/__main__.py
      - uses: actions/upload-artifact@v2
      with:
        name: MeshFlash
        path: dist/windows
