name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install MeshFlash from local
        run: |
          pip3 install .
      - name: Validate we can run it
        run: |
          meshflash -h
