name: Publish PyPI

on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Install pyinstaller
        run: |
          pip install pyinstaller
      - name: Build exe
        run: |
          pyinstaller -F -n MeshFlash MeshFlash/__main__.py
      - uses: actions/upload-artifact@v2
        with:
          name: MeshFlash
          path: dist/windows

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
